version: 0.2 

phases:
    install: 
        runtime-versions: 
            nodejs: 14 
        commands: 
            - echo "installing something" 
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    pre_build:
        commands: 
            - echo "we are in the pre build phase" 
    build:
        commands: 
            - echo "we are in the build block"
            #- ng build --prod
            #- echo "we will run some tests" 
    post_build:
        commands: 
            - echo "we are in the post build phase"
